name: example-workflow.yml
on:
  workflow_dispatch:

jobs:
  start-runner:
    name: Start EC2 runner
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.start-ec2-runner.outputs.runner-label }}
      instance-id: ${{ steps.start-ec2-runner.outputs.instance-id }}
    steps:
      - uses: actions/create-github-app-token@v1 # For configuring the self-hosted runner
        id: generate_token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/YourGitHubActionsRoleHere
          aws-region: ${{ vars.AWS_REGION }}
      - name: Get runner registration token
        id: generate_runner_registration_token
        run: |
          owner_repo="${GITHUB_REPOSITORY}"  # Format: owner/repo
          github_token=${{ steps.generate_token.outputs.token }}

          response=$(curl -L -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${github_token}" \
              "https://api.github.com/repos/${owner_repo}/actions/runners/registration-token")

          # Check if the curl command was successful
          if [ $? -eq 0 ]; then
              # Extract token using string manipulation (basic approach)
              token=$(echo "$response" | grep -o '"token":\s*"[^"]*' | cut -d'"' -f4)

              if [ -n "$token" ]; then
                  echo "::add-mask::$token"
                  echo "runner_registration_token=$token" >> "$GITHUB_OUTPUT"
              else
                  echo "Error: Failed to extract token from response $response" >&2
                  exit 1
              fi
          else
              echo "Error: Failed to get GitHub Registration Token" >&2
              exit 1
          fi
      - name: Launch EC2 Runner
        id: start-ec2-runner
        uses: gingercybersecurity/provision-ec2-runner
        with:
          github-runner-registration-token: ${{ steps.generate_runner_registration_token.outputs.runner_registration_token }}
          subnet-id: ${{ vars.AWS_SUBNET_ID }} # subnet-abcde
          security-group-id: ${{ vars.AWS_SECURITY_GROUP_ID }} # sg-abcde
          ami-id: ${{ vars.AWS_AMI_ID }} # ami-abcde
          instance-type: t3.micro
          key-name: ${{ vars.AWS_KEY_NAME }}
          tag-name: 'ManagedBy'
          tag-value: 'github-actions'
          iam-instance-profile: 'CloudWatchLogger'

  test:
    name: Run Tests
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.runner-label }}
    steps:
      - name: Run Tests
        run: |
          echo "Tests go here"

  stop-runner:
    name: Stop EC2 runner
    # Always stop the runner regardless of workflow failure or cancellation
    if: ${{ always() }}
    needs:
      - start-runner
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate_token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/YourGitHubActionsRoleHere
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run EC2 Stop
        uses: gingercybersecurity/terminate-ec2-runner
        with:
          instance-id: ${{ needs.start-runner.outputs.instance-id }}
