name: example-workflow.yml
on:
  workflow_dispatch:

jobs:
  start-runner:
    name: Start EC2 runner
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.start-ec2-runner.outputs.runner-label }}
      instance-id: ${{ steps.start-ec2-runner.outputs.instance-id }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1 # For configuring the self-hosted runner
        id: generate_token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/YourGitHubActionsRoleHere
          aws-region: ${{ vars.AWS_REGION }}
      - name: Launch EC2 Runner
        id: start-ec2-runner
        uses: gingercybersecurity/provision-ec2-runner
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          subnet-id: subnet-abcde
          security-group-id: sg-abcde
          ami-id: ami-abcde
          instance-type: t3.micro
          key-name: github-runner
          tag-name: 'ManagedBy'
          tag-value: 'github-actions'

  test:
    name: Run Tests
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.runner-label }}
    steps:
      - name: Run Tests
        run: |
          echo "Tests go here"

  stop-runner:
    name: Stop EC2 runner
    # Always stop the runner regardless of workflow failure or cancellation
    if: ${{ always() }}
    needs:
      - start-runner
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: generate_token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/YourGitHubActionsRoleHere
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run EC2 Stop
        uses: gingercybersecurity/terminate-ec2-runner
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          runner-label: ${{ needs.start-runner.outputs.runner-label }}
          instance-id: ${{ needs.start-runner.outputs.instance-id }}
